### ISSUE TITLE
understanding events?

### ISSUE THREAD

**Issue by dpastoor** [nlmixrdevelopment/RxODE#1]
Hi all,

Nice work so far. Taking a look at the example, I'm trying to wrap my head around where/how an event system is in place. 

Two cases come to mind

1) a discrete event, that varies by individual so couldn't be 'hard coded' as something like

```
if (time == 5) // do thing
```

2) along those same lines, how would a time-varying covariate be implemented.

for example, given an individual clearance that is dependent on EGFR, I would parameterize such as something like:

```
CL = TVCL*EGFR/NORM_EGFR^EXP_EGFR
```

but if the resulting CL was a vector of values that change over time, how can RxODE consume such a scenario?

Thanks!

**Comment by mattfidler** [comment]
Thanks @dpastoor .  I have seen how you contributed greatly to the mrgsolve package, and I'm happy to answer any questions you have about RxODE.  You seem like a very talented R programmer.

I'm a bit confused about your first question.  If a discrete event, like a dose, varies in an individual you would have a different event table for that individual.  Are you asking about dynamic events?

As far as your second question, time varying co-variates are already included in the development version of RxODE with two different types of interpolations, linear and last observation carried forward.  This interpolation is needed because the solving engine will pick values in-between the observed co-variate values to solve the ODE.

To specify the time-varying covariates, you pass the dataset with the time-varying covariates for that individual to the solving engine by the `covs` option.

In the testing suite is a very superficial example is:

```R
ode <- RxODE({
        b       = -1
        d/dt(X) = a*X + Y*Z;
        d/dt(Y) = b*(Y - Z);
        d/dt(Z) = -X*Y + c*Y - Z
        printf("%.10f,%.10f\n",t,c);
    })

    et <- eventTable()   # default time units
    et$add.sampling(seq(from=0, to=100, by=0.01))

    cov <- data.frame(c=et$get.sampling()$time+1);
```

Then for that individual you could solve using the time-varying covariates by:

```R
out <- rxSolve(ode,
                   params = c(a=-8/3, b=-10),
                   events = et,
                   inits = c(X=1, Y=1, Z=1),
                   covs = cov);
```

or with the `%>%` syntax and `solve` routine (which I like):

```R
out <- ode %>% solve(params = c(a=-8/3, b=-10),
                   events = et,
                   inits = c(X=1, Y=1, Z=1),
                   covs = cov);
```

I have been thinking of adjusting this routine so that factors like gender and continuous covariates like GFR would have different types of interpolation, but I haven't gotten around to it yet.

**Comment by dpastoor** [comment]
Thanks for the info! to clarify on 1, I was thinking of non-dose-related events.

case:

a series of times available for an individual in which they started/stopped dialysis. I presume I could just overload the covs implementation using something like

```
// pseudocoded parameterization inside RxODE
CL = CL + 3*on_dial

et$add.sampling(c(0, 5, 7)
cov <- data_frame(on_dial = c(0, 1, 0))
```

am I on the right track?


Does sampling mean that that is also going to be the times output? can you cut down on that without spitting everything back to R. I'm thinking of situations where the timescales can be longer

something like

```
solve(..., delta = 1, # only sample at time intervals of 1)
 ```

or

```
solve(..., obs = seq(0, 10, 3))
```

Especially in cases where there are a lot of events that don't need direct observation (each change in a timevarying covariate for example) I wouldn't necessary want/need all sample times to be pushed out.

I do understand this is (premature) optimization of a sort, but was just wondering if it was implemented?

**Comment by mattfidler** [comment]
I'm not sure if I understand everything correctly, but this sort of thing can be updated dynamically.

This can be done like:

```R
ode <- "
   C2 = centr/V2;
   C3 = peri/V3;
   d/dt(depot) =-KA*depot;
   d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
   d/dt(peri)  =                    Q*C2 - Q*C3;
   d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
"
mod1 <- RxODE(ode)
 theta <- 
   c(KA=2.94E-01, CL=1.86E+01, V2=4.02E+01, # central 
     Q=1.05E+01,  V3=2.97E+02,              # peripheral
     Kin=1, Kout=1, EC50=200)               # effects  
inits <- c(eff=1);
ev <- eventTable(amount.units='mg', time.units='hours')

ev$add.dosing(dose=10000, nbr.doses=10, dosing.interval=12)
ev$add.dosing(dose=20000, nbr.doses=5, start.time=120, dosing.interval=24)
ev$add.sampling(0:240)

x <- mod1 %>% solve(theta, ev, inits)
```

Then say you want to have an observation every 30 minutes:

```
x$time <- seq(0,240,by=0.5)
```

**Comment by mattfidler** [comment]
You can also update parameters this way

```R
x$KA = 0.4
```

**Comment by mattfidler** [comment]
And yes, your time-varying covariate can be used to dynamically change the CL as you showed.

**Comment by mattfidler** [comment]
I also don't know if the time-varying covariates have to have the same sampling time as the observations. 

I have forgotten if the code requires this or not.

**Comment by mattfidler** [comment]
You could also send a new event table to the object, by assigning the `x$events` object.  I think you can also resolve using `solve(...,events=)`

**Comment by mattfidler** [comment]
I believe you are on the right track for the dialysis case.  It similar to NONMEM in that regard.

As far as changing the time-scales, with the development version you can change your observations easily.

```

**Comment by mattfidler** [comment]
You could also hard-code different things, because RxODE does support the `if` `else` syntax.
