### ISSUE TITLE
New windows toolchain fails for RxODE

### ISSUE THREAD

**Issue by mattfidler** [nlmixrdevelopment/RxODE#146]
https://github.com/r-windows/checks/issues/86

**Comment by mattfidler** [comment]
Actually this is:

https://github.com/r-windows/checks/issues/84

**Comment by jeroen** [comment]
Just to emphasize, you really should be overriding the toolchain settings by setting PATH and BINPREF from within R. Each version of R has been configured against a certain toolchain and the appropriate compiler will be used via make variables `$(CC)` `$(CXX)` etc.

To lookup the appropriate compiler with a system command you can use e.g.

```
R CMD config CC
```

But make sure you get the correct R because a server may have many versions of R installed and the one on the PATH might not be the one you need. You can use `R.home` to find the current R:

```r
system2(file.path(R.home("bin"), 'Rcmd'), c("config", "CC"), stdout=TRUE)
```

**Comment by mattfidler** [comment]
Thanks @jeroen for the tips.  I will look into it.
