### ISSUE TITLE
How to incorporate TAD in RxODE simulation?

### ISSUE THREAD

**Issue by akurumaddali** [nlmixrdevelopment/RxODE#491]
I'm trying to code a model component (of a Pop PK model) which is a function of TIME (actual relative time from the first dose) or Time after dose (TAD: actual relative time from the previous dose ) as follows:

FUNC1 = a + b*exp(-beta * TAD)

FUNC2 = a + b*exp(-beta * TIME)

When I used FUNC1, TAD is a part of the mod$params of the model. When I replaced FUNC1 with FUNC2, TAD is replaced by TIME in mod$params.

I've included both TIME (actual relative time from the first dose) as well as TAD (actual relative time from the previous dose) within the "samp" data frame as well as the "dose" data frame.

While the simulation runs smoothly when using FUNC2, it throws an error saying that "The following parameter(s) are required for solving: TAD" when I use FUNC1.

Can you please help resolve this issue? Thanks in advance.

**Comment by mattfidler** [comment]
Hi, 

I don't know when this was added, but you can use `t` and `time` in `rxode2`, which will give the actual time linearized instead of interpolated `TIME` from the dataset.

For `TAD` you could calculate it yourself or use `tad()` or even `tad(cmt)`.

This should be available in the documentation of `rxode2` syntax:

https://nlmixr2.github.io/rxode2/articles/rxode2-syntax.html#supported-functions
