### ISSUE TITLE
Regression when specifying initial conditions in the model

### ISSUE THREAD

**Issue by rfaelens** [nlmixrdevelopment/RxODE#67]
When I run the following code, I would expect SLD starts at a baseline value of +- 14.3.
```
modelCode <- "
TVBASE=14.3;
BASE=TVBASE*exp(EBASE);
SLD(0)=BASE;
d/dt(SLD)=-0.5*SLD;
"
m1 <- RxODE(modelCode)
ev <- eventTable() %>% add.sampling(c(0, 1))
rxSolve(m1, ev, params=c(EBASE=0.3))
```

This is indeed the case in version 0.8.0-9, but not in the current `master` on github. It seems initialization of parameters based on input values does not work in the current `master`.

**Comment by mattfidler** [comment]
Indeed.  I am about to merge the mevent2 branch onto the master branch.  I think that one works correctly.

**Comment by mattfidler** [comment]
There are some breaking changes in this new version, notably:

# Units
Units are actually now handled correctly in event tables (which now support NONMEM data standards).  

This can be a problem when trying to subset or do data manipulation because the units tries to convert and only allows operations between two different types of units;  `drop_units` can help here.

# Covariates

Solving covariates require them to be on the data.frame sent to RxODE now, you cannot specify them in a separate argument.

**Comment by mattfidler** [comment]
Also the new features (bioavailibility, lag time, mtime, etc) are not documented well and do not work with nlmixr.

**Comment by mattfidler** [comment]
If this update does not work for you, let me know.  For now I'm closing the issue.

**Comment by rfaelens** [comment]
Update works very well. If I ever find the time, I may contribute some documentation.
Thanks again!

**Comment by mattfidler** [comment]
Please do :)

The beta data features are documented here:

https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-events.html#event-types-for-rxode
